# Branch naming convention
# Format: <type>/<description>
# 
# Types:
# - feature/     : New features
# - bugfix/      : Bug fixes
# - hotfix/      : Critical fixes for production
# - release/     : Release preparation
# - docs/        : Documentation updates
# - refactor/    : Code refactoring
# - test/        : Test improvements
# - perf/        : Performance improvements
# - ci/          : CI/CD improvements

# Examples:
# - feature/order-matching-engine
# - bugfix/memory-leak-in-orderbook
# - hotfix/critical-trading-bug
# - release/v1.0.0
# - docs/api-documentation
# - refactor/market-class-structure
# - test/add-orderbook-tests
# - perf/optimize-order-insertion
# - ci/add-gcc15-workflow 