// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: market.proto

#include "market.pb.h"
#include "market.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace market {

static const char* Market_method_names[] = {
  "/market.Market/PlaceOrder",
  "/market.Market/GetOrderStatus",
  "/market.Market/CancelOrder",
};

std::unique_ptr< Market::Stub> Market::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Market::Stub> stub(new Market::Stub(channel, options));
  return stub;
}

Market::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PlaceOrder_(Market_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOrderStatus_(Market_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelOrder_(Market_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Market::Stub::PlaceOrder(::grpc::ClientContext* context, const ::market::PlaceOrderRequest& request, ::market::OrderId* response) {
  return ::grpc::internal::BlockingUnaryCall< ::market::PlaceOrderRequest, ::market::OrderId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PlaceOrder_, context, request, response);
}

void Market::Stub::async::PlaceOrder(::grpc::ClientContext* context, const ::market::PlaceOrderRequest* request, ::market::OrderId* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::market::PlaceOrderRequest, ::market::OrderId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlaceOrder_, context, request, response, std::move(f));
}

void Market::Stub::async::PlaceOrder(::grpc::ClientContext* context, const ::market::PlaceOrderRequest* request, ::market::OrderId* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlaceOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::market::OrderId>* Market::Stub::PrepareAsyncPlaceOrderRaw(::grpc::ClientContext* context, const ::market::PlaceOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::market::OrderId, ::market::PlaceOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PlaceOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::market::OrderId>* Market::Stub::AsyncPlaceOrderRaw(::grpc::ClientContext* context, const ::market::PlaceOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPlaceOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Market::Stub::GetOrderStatus(::grpc::ClientContext* context, const ::market::OrderId& request, ::market::LimitOrderInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::market::OrderId, ::market::LimitOrderInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOrderStatus_, context, request, response);
}

void Market::Stub::async::GetOrderStatus(::grpc::ClientContext* context, const ::market::OrderId* request, ::market::LimitOrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::market::OrderId, ::market::LimitOrderInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrderStatus_, context, request, response, std::move(f));
}

void Market::Stub::async::GetOrderStatus(::grpc::ClientContext* context, const ::market::OrderId* request, ::market::LimitOrderInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrderStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::market::LimitOrderInfo>* Market::Stub::PrepareAsyncGetOrderStatusRaw(::grpc::ClientContext* context, const ::market::OrderId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::market::LimitOrderInfo, ::market::OrderId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOrderStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::market::LimitOrderInfo>* Market::Stub::AsyncGetOrderStatusRaw(::grpc::ClientContext* context, const ::market::OrderId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOrderStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Market::Stub::CancelOrder(::grpc::ClientContext* context, const ::market::OrderId& request, ::market::CancelOrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::market::OrderId, ::market::CancelOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelOrder_, context, request, response);
}

void Market::Stub::async::CancelOrder(::grpc::ClientContext* context, const ::market::OrderId* request, ::market::CancelOrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::market::OrderId, ::market::CancelOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void Market::Stub::async::CancelOrder(::grpc::ClientContext* context, const ::market::OrderId* request, ::market::CancelOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::market::CancelOrderResponse>* Market::Stub::PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::market::OrderId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::market::CancelOrderResponse, ::market::OrderId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::market::CancelOrderResponse>* Market::Stub::AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::market::OrderId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

Market::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Market_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Market::Service, ::market::PlaceOrderRequest, ::market::OrderId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Market::Service* service,
             ::grpc::ServerContext* ctx,
             const ::market::PlaceOrderRequest* req,
             ::market::OrderId* resp) {
               return service->PlaceOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Market_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Market::Service, ::market::OrderId, ::market::LimitOrderInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Market::Service* service,
             ::grpc::ServerContext* ctx,
             const ::market::OrderId* req,
             ::market::LimitOrderInfo* resp) {
               return service->GetOrderStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Market_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Market::Service, ::market::OrderId, ::market::CancelOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Market::Service* service,
             ::grpc::ServerContext* ctx,
             const ::market::OrderId* req,
             ::market::CancelOrderResponse* resp) {
               return service->CancelOrder(ctx, req, resp);
             }, this)));
}

Market::Service::~Service() {
}

::grpc::Status Market::Service::PlaceOrder(::grpc::ServerContext* context, const ::market::PlaceOrderRequest* request, ::market::OrderId* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Market::Service::GetOrderStatus(::grpc::ServerContext* context, const ::market::OrderId* request, ::market::LimitOrderInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Market::Service::CancelOrder(::grpc::ServerContext* context, const ::market::OrderId* request, ::market::CancelOrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace market
#include <grpcpp/ports_undef.inc>

