name: Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=23 -DCLOB_BUILD_TESTS=ON -DCLOB_CODE_COVERAGE=ON -DCLOB_VERBOSE_MAKEFILE=ON

    - name: Build
      run: cmake --build build -j4

    - name: Test
      run: |
        cd build
        ctest --build-config Debug

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true